#' Append package information to user agent
#'
#' Add information about nectar and the calling package (if called from a
#' package) to the user agent string.
#'
#' @inheritParams .shared-params
#' @inherit .shared-request return
#' @export
#' @examples
#' req <- httr2::request("https://example.com")
#' req$options$useragent
#' req_pkg_user_agent(req)$options$useragent
#' req_pkg_user_agent(req, "stbl")$options$useragent
req_pkg_user_agent <- function(req,
                               pkg_name = get_pkg_name(call),
                               pkg_url = NULL,
                               call = rlang::caller_env()) {
  # Always include nectar since we're the ones doing this.
  user_agent_string <- .nectar_user_agent_append(
    existing_user_agent = req$options$useragent %||%
      .httr2_default_user_agent(),
    call = call
  )
  if (length(pkg_name) && pkg_name != "nectar") {
    user_agent_string <- .pkg_user_agent_append(
      existing_user_agent = user_agent_string,
      pkg_name = pkg_name,
      pkg_url = pkg_url,
      call = call
    )
  }
  return(
    httr2::req_user_agent(req, string = user_agent_string)
  )
}

#' Append package user agent
#'
#' @inheritParams .shared-params
#' @returns A string to use as a user agent. Attach the agent to your request
#'   with [httr2::req_user_agent()].
#' @keywords internal
.pkg_user_agent_append <- function(existing_user_agent = NULL,
                                   pkg_name = get_pkg_name(call),
                                   pkg_url = NULL,
                                   call = rlang::caller_env()) {
  .lib_user_agent_append(
    existing_user_agent,
    name = pkg_name,
    version = .get_pkg_version(pkg_name, call = call),
    url = pkg_url,
    call = call
  )
}

#' Generate library user agent string
#'
#' @inheritParams .shared-params
#' @returns A user agent string for the library.
#' @keywords internal
.lib_user_agent_string <- function(name,
                                   version,
                                   url = NULL,
                                   call = rlang::caller_env()) {
  name <- stabilize_string(name, call = call)
  agent <- glue::glue("{name}/{version}")
  url <- stbl::to_chr_scalar(url, call = call)
  if (length(url)) {
    agent <- glue::glue("{agent} ({url})")
  }
  return(agent)
}

#' Add a library and version to a user agent
#'
#' @inheritParams .shared-params
#' @returns A modified user agent string for the library.
#' @keywords internal
.lib_user_agent_append <- function(existing_user_agent,
                                   name,
                                   version,
                                   url = NULL,
                                   call = rlang::caller_env()) {
  if (is.null(name)) {
    return(existing_user_agent)
  }
  lib_string <- .lib_user_agent_string(name, version, url = url, call = call)
  existing_user_agent <- .user_agent_remove(
    existing_user_agent,
    name = name,
    url = url,
    call = call
  )
  return(
    glue::glue_collapse(c(existing_user_agent, lib_string), sep = " ")
  )
}

#' Create a nectar user agent string
#'
#' Create or modify a user agent string to identify that a request used the
#' nectar package.
#'
#' @inheritParams .shared-params
#' @returns A string to use as a user agent, with the nectar user agent
#'   prepended exactly once.
#' @keywords internal
.nectar_user_agent_append <- function(existing_user_agent = NULL,
                                      call = rlang::caller_env()) {
  return(
    .pkg_user_agent_append(
      pkg_name = "nectar",
      existing_user_agent = existing_user_agent,
      pkg_url = "https://nectar.api2r.org",
      call = call
    )
  )
}

#' Extract the httr2 default user agent
#'
#' @returns The user agent string generated by the installed version of httr2.
#' @keywords internal
.httr2_default_user_agent <- function() {
  httr2::req_user_agent(httr2::request(""))$options$useragent
}

#' Remove package and version from user agent
#'
#' @inheritParams .shared-params
#' @returns A modified user agent string, minus `name`, any associated version,
#'   and the `url`.
#' @keywords internal
.user_agent_remove <- function(existing_user_agent,
                               name,
                               url = NULL,
                               call = rlang::caller_env()) {
  existing_user_agent <- stbl::to_chr_scalar(existing_user_agent, call = call)
  if (!length(existing_user_agent)) {
    return(existing_user_agent)
  }
  # Order of removal matters. Go from most specific to least specific.
  if (length(url)) {
    url <- stabilize_string(url, call = call)
    existing_user_agent <- stringr::str_remove(existing_user_agent, url)
  }
  name <- stabilize_string(name, call = call)
  existing_user_agent <- stringr::str_remove(
    existing_user_agent,
    paste0(name, "/[^ ]+")
  )
  existing_user_agent <- stringr::str_remove(existing_user_agent, name)
  existing_user_agent <- stringr::str_remove_all(
    existing_user_agent,
    "\\(\\s*\\)"
  )
  return(stringr::str_squish(existing_user_agent))
}
